# Generated by Django 5.0.6 on 2024-06-24 21:53

import django_multipart_upload.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutipartFileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "file",
                    django_multipart_upload.fields.MultipartFileField(
                        upload_to="files/"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(upload_to="files/"),
        ),
    ]
